"""Shared controller state constants."""

MODE_NORMAL_DRIVE = "NORMAL_DRIVE"
MODE_SLOW_APPROACH = "SLOW_APPROACH"
MODE_ROTATE_IN_PLACE = "ROTATE_IN_PLACE"
MODE_OBSTACLE_STOP = "OBSTACLE_STOP"
MODE_EMERGENCY_STOP = "EMERGENCY_STOP"

